extern crate cbindgen;

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let config = {
        let mut c: cbindgen::Config = Default::default();
        c.header = Some(concat!(
  "// THIS FILE IS AUTOGENERATED BY mp4parse-rust/build.rs - DO NOT EDIT\n\n",
  "// This Source Code Form is subject to the terms of the Mozilla Public\n",
  "// License, v. 2.0. If a copy of the MPL was not distributed with this\n",
  "// file, You can obtain one at https://mozilla.org/MPL/2.0/.",
        ).to_owned());
        c
    };

    println!("cargo:rerun-if-changed=src/lib.rs");
    // Generate mp4parse.h.
    cbindgen::generate_with_config(&crate_dir, config)
        .expect("Could not generate header")
        .write_to_file("include/mp4parse.h");
}
